server {
    listen 80;
    server_name _;

    underscores_in_headers on;

    location / {
        proxy_pass http://app:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /ws/soil {
        proxy_pass http://app:8080;

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;

        proxy_pass_request_headers on;

        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;

        proxy_buffers 8 32k;
        proxy_buffer_size 64k;
    }
}